# Generated by Django 4.1.3 on 2023-03-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
