# Generated by Django 4.1.3 on 2023-03-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_customer_details_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField()),
                ('bnumber', models.PositiveIntegerField()),
                ('bname', models.CharField(max_length=30)),
                ('bus_from', models.CharField(max_length=30)),
                ('bus_to', models.CharField(max_length=30)),
            ],
        ),
    ]
