# Generated by Django 4.1.3 on 2023-03-20 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_bus_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_list',
            name='bid',
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('busid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.bus_list')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.customer_details')),
            ],
        ),
    ]
